### ISSUE TITLE
bro complicate his life

### ISSUE THREAD

**Issue by Vadraidk** [Gobbka/GBHRC#2]
why u dont use C# mono injection for the cheat??????????????????????? why do a shit take 2 month in C++ bruh

or why just dont use mono_field shit ?????

**Comment by Gobbka** [comment]
Долбаеб тебе какое деле до моего Чита ёпта?
Иди подрочи лучше

**Comment by Vadraidk** [comment]
> Долбаеб тебе какое деле до моего Чита ёпта? Иди подрочи лучше

idk who is but isnt me, but whatever search "ifackbp_xd" on youtube x)
